/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
    docs: [
        'about',
        'getting-started',
        'examples',
        {
            type: 'category',
            label: 'Recipes',
            link: { type: 'doc', id: 'recipes' },
            collapsed: true,
            collapsible: true,
            items: [
                'recipes-leader-latch',
                'recipes-leader-election',
                'recipes-shared-reentrant-lock',
                'recipes-shared-lock',
                'recipes-shared-reentrant-read-write-lock',
                'recipes-shared-semaphore',
                'recipes-multi-shared-lock',
                'recipes-barrier',
                'recipes-double-barrier',
                'recipes-shared-counter',
                'recipes-distributed-atomic-long',
                'recipes-curator-cache',
                'recipes-path-cache',
                'recipes-node-cache',
                'recipes-tree-cache',
                'recipes-persistent-watcher',
                'recipes-persistent-node',
                'recipes-persistent-ttl-node',
                'recipes-group-member',
                'recipes-distributed-queue',
                'recipes-distributed-id-queue',
                'recipes-distributed-priority-queue',
                'recipes-distributed-delay-queue',
                'recipes-simple-distributed-queue',
            ],
        },
        'async',
        'modeled',
        'migrations',
        'schema',
        { type: 'html', defaultStyle: true, value: 'LOW LEVEL' },
        'framework',
        'utilities',
        'client',
        { type: 'html', defaultStyle: true, value: 'DETAILS' },
        'errors',
        'logging',
        {
            type: 'category',
            label: 'Tech Notes',
            link: { type: 'doc', id: 'tech-notes' },
            collapsed: true,
            collapsible: true,
            items: [
                'tech-note-01',
                'tech-note-02',
                'tech-note-03',
                'tech-note-04',
                'tech-note-05',
                'tech-note-06',
                'tech-note-07',
                'tech-note-08',
                'tech-note-09',
                'tech-note-10',
                'tech-note-11',
                'tech-note-12',
                'tech-note-13',
                'tech-note-14',
                'tech-note-15',
            ],
        },
        'zk-compatibility-34',
        'breaking-changes',
        { type: 'link', label: 'Javadoc', href: 'pathname:///apidocs/' },
        { type: 'link', label: 'Wiki', href: 'https://cwiki.apache.org/confluence/display/CURATOR' },
        { type: 'html', defaultStyle: true, value: 'EXTENSIONS' },
        'service-discovery',
        'service-discovery-server',
    ],
};

module.exports = sidebars;
